# Generated by Django 3.0.8 on 2020-08-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('selected', models.BooleanField(default=False)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
